### ISSUE TITLE
主页问题请教

### ISSUE THREAD

**Issue by xutingyin** [Jackson0714/PassJava-Platform#7]
请问下你的这个主页是用什么做的哇~
http://www.jayh.club/#/

**Comment by Jackson0714** [comment]
@xutingyin 我在这篇文章中写到了 https://juejin.im/post/6844904115466682375

**Comment by xutingyin** [comment]
好的，多谢

**Comment by xutingyin** [comment]
@Jackson0714  好的，多谢。
